/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 optimized-room.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { EffectComposer, SelectiveBloom } from "@react-three/postprocessing";
import { BlendFunction } from "postprocessing";
import * as THREE from "three";

export function Room(props) {
  const { nodes, materials } = useGLTF("/models/optimized-room.glb");
  const screensRef = useRef();

  /* ------------------ Materials (Clean & Minimal) ------------------ */
  const darkMaterial = new THREE.MeshStandardMaterial({
    color: "#0f0f0f",
    roughness: 0.6,
    metalness: 0.1,
  });

  const lightMaterial = new THREE.MeshStandardMaterial({
    color: "#ffffff",
    roughness: 0.4,
    metalness: 0.2,
  });

  const accentMaterial = new THREE.MeshStandardMaterial({
    color: "#6c63ff",
    roughness: 0.3,
    metalness: 0.4,
  });

  return (
    <group {...props} dispose={null}>
      {/* ------------------ Post Processing ------------------ */}
      <EffectComposer>
        <SelectiveBloom
          selection={screensRef}
          intensity={1} // softer = premium
          luminanceThreshold={0.35}
          luminanceSmoothing={0.8}
          blendFunction={BlendFunction.ADD}
        />
      </EffectComposer>

      {/* ------------------ Scene Meshes ------------------ */}
      <mesh
        geometry={nodes._________6_blinn1_0.geometry}
        material={accentMaterial}
      />
      <mesh geometry={nodes.body1_blinn1_0.geometry} material={darkMaterial} />
      <mesh geometry={nodes.cabin_blinn1_0.geometry} material={darkMaterial} />
      <mesh
        geometry={nodes.chair_body_blinn1_0.geometry}
        material={darkMaterial}
      />

      <mesh geometry={nodes.comp_blinn1_0.geometry} material={lightMaterial} />

      {/* Screens / Emissive */}
      <mesh
        ref={screensRef}
        geometry={nodes.emis_lambert1_0.geometry}
        material={materials.lambert1}
      />

      {/* Reused base materials */}
      <mesh
        geometry={nodes.keyboard_blinn1_0.geometry}
        material={darkMaterial}
      />
      <mesh geometry={nodes.miuse_blinn1_0.geometry} material={darkMaterial} />
      <mesh
        geometry={nodes.monitor2_blinn1_0.geometry}
        material={darkMaterial}
      />
      <mesh
        geometry={nodes.monitor3_blinn1_0.geometry}
        material={darkMaterial}
      />
      <mesh geometry={nodes.table_blinn1_0.geometry} material={darkMaterial} />
      <mesh geometry={nodes.tablet_blinn1_0.geometry} material={darkMaterial} />

      <mesh
        geometry={nodes.pillows_blinn1_0.geometry}
        material={accentMaterial}
      />
      <mesh
        geometry={nodes.radiator_blinn1_0.geometry}
        material={lightMaterial}
      />
      <mesh
        geometry={nodes.window_blinn1_0.geometry}
        material={lightMaterial}
      />
    </group>
  );
}

useGLTF.preload("/models/optimized-room.glb");
